name: deploy with surge

on:
  push:
    branches: [ master ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup nodejs
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: setup surge
      run: npm install -g surge
    - name: excute surge
      run: surge ./ http://pakbootcamp-class1.surge.sh/ --token ${{secrets.SURGE_TOKEN}}

